var mongoose = require('mongoose');
var Schema = mongoose.Schema;

/* application form model */
var applicationFormSchema = new Schema({
    category: { type: String, lowercase: true, trim: true },
    course: { type: String, lowercase: true, trim: true },
    name_as_per_ssc_hsc: { type: String, lowercase: true, trim: true },
    dob: { type: Date },
    fname: { type: String, lowercase: true, trim: true },
    mname: { type: String, lowercase: true, trim: true },
    lname: { type: String, lowercase: true, trim: true },
    gender: { type: Boolean },
    maritial_status: { type: String, lowercase: true, trim: true },
    place_of_birth: { type: String, lowercase: true, trim: true },
    nationality: { type: String, lowercase: true, trim: true },
    religion: { type: String, lowercase: true, trim: true },
    sub_caste: { type: String, lowercase: true, trim: true },
    mother_tongue: { type: String, lowercase: true, trim: true },
    aadhar_number: { type: String, lowercase: true, trim: true },
    blood_group: { type: String, lowercase: true, trim: true },
    phoneno: { type: String, lowercase: true, trim: true },
    email: { type: String, lowercase: true, trim: true },
    telephpne: { type: String, lowercase: true, trim: true },
    sports: { type: String, lowercase: true, trim: true },
    extra_curricular: { type: String, lowercase: true, trim: true },
    disability : { type: String, lowercase: true, trim: true },
    father_name : { type: String, lowercase: true, trim: true },
    father_qualification : { type: String, lowercase: true, trim: true },
    father_occupation : { type: String, lowercase: true, trim: true },
    family_annual_income : { type: String, lowercase: true, trim: true },
    father_mobileno : { type: String, lowercase: true, trim: true },
    mother_name : { type: String, lowercase: true, trim: true },
    mother_qualification : { type: String, lowercase: true, trim: true },
    mother_occupation : { type: String, lowercase: true, trim: true },
    mother_mobileno : { type: String, lowercase: true, trim: true },
    guardian_name : { type: String, lowercase: true, trim: true },
    guardian_qualification : { type: String, lowercase: true, trim: true },
    guardian_occupation : { type: String, lowercase: true, trim: true },
    guardian_mobileno : { type: String, lowercase: true, trim: true },
    ssc_examination : { type: String, lowercase: true, trim: true },
    ssc_board_university : { type: String, lowercase: true, trim: true },
    ssc_school_college : { type: String, lowercase: true, trim: true },
    ssc_seat_roll_no : { type: String, lowercase: true, trim: true },
    ssc_passing_year : { type: String, lowercase: true, trim: true },
    ssc_marks_obtained : { type: String, lowercase: true, trim: true },
    ssc_marks_out_of : { type: String, lowercase: true, trim: true },
    ssc_percentage : { type: String, lowercase: true, trim: true },
    hsc_examination : { type: String, lowercase: true, trim: true },
    hsc_board_university : { type: String, lowercase: true, trim: true },
    hsc_school_college : { type: String, lowercase: true, trim: true },
    hsc_seat_roll_no : { type: String, lowercase: true, trim: true },
    hsc_passing_year : { type: String, lowercase: true, trim: true },
    hsc_marks_obtained : { type: String, lowercase: true, trim: true },
    hsc_marks_out_of : { type: String, lowercase: true, trim: true },
    hsc_percentage : { type: String, lowercase: true, trim: true },
    sem_one_examination : { type: String, lowercase: true, trim: true },
    sem_one_board_university : { type: String, lowercase: true, trim: true },
    sem_one_school_college : { type: String, lowercase: true, trim: true },
    sem_one_seat_roll_no : { type: String, lowercase: true, trim: true },
    sem_one_sgpa : { type: String, lowercase: true, trim: true },
    sem_one_grade : { type: String, lowercase: true, trim: true },
    sem_two_examination : { type: String, lowercase: true, trim: true },
    sem_two_board_university : { type: String, lowercase: true, trim: true },
    sem_two_school_college : { type: String, lowercase: true, trim: true },
    sem_two_seat_roll_no : { type: String, lowercase: true, trim: true },
    sem_two_sgpa : { type: String, lowercase: true, trim: true },
    sem_two_grade : { type: String, lowercase: true, trim: true },
    correspondence_flat_apartment : { type: String, lowercase: true, trim: true },
    correspondence_country : { type: String, lowercase: true, trim: true },
    correspondence_state: { type: String, lowercase: true, trim: true },
    correspondence_district: { type: String, lowercase: true, trim: true },
    correspondence_city: { type: String, lowercase: true, trim: true },
    correspondence_pincode: { type: String, lowercase: true, trim: true },
    permanent_flat_apartment : { type: String, lowercase: true, trim: true },
    permanent_country : { type: String, lowercase: true, trim: true },
    permanent_state: { type: String, lowercase: true, trim: true },
    permanent_district: { type: String, lowercase: true, trim: true },
    permanent_city: { type: String, lowercase: true, trim: true },
    permanent_pincode: { type: String, lowercase: true, trim: true },
    aahar_card: { type: String, lowercase: true, trim: true },
    ration_card: { type: String, lowercase: true, trim: true },
    sem_one_three: { type: String, lowercase: true, trim: true },
    sem_two_four: { type: String, lowercase: true, trim: true },
    signature: { type: String, lowercase: true, trim: true },
    picture: { type: String, lowercase: true, trim: true },
    accept_terms: { type: Boolean, default: false },
    updated_at: { type: Date, default: Date.now },
    status: { type: Boolean, default: true },
    status: { type: Boolean, default: true },
    user: { type: Schema.Types.ObjectId, ref: 'Users' },
});

module.exports = User = mongoose.model('ApplicationForm', applicationFormSchema);